import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: [
        {type: 'doc', id: 'introduction/getting-started'},
        {type: 'doc', id: 'introduction/runtime-compatibility'},
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/concepts',
        description:
          'Core concepts behind WebSpatial, spatial computing, scenes, interactions, and 2D + 3D composition.',
      },
      items: [{type: 'autogenerated', dirName: 'concepts'}],
    },
    {
      type: 'category',
      label: 'How-to',
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: '/how-to',
        description:
          'Practical setup guides for PWA requirements, JSX runtime configuration, SSR, Xcode, and app-store workflows.',
      },
      items: [{type: 'autogenerated', dirName: 'how-to'}],
    },
    {
      type: 'category',
      label: 'API',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/api',
        description:
          'Reference docs for WebSpatial Builder and the WebSpatial React SDK.',
      },
      items: [{type: 'autogenerated', dirName: 'api'}],
    },
  ],
};

export default sidebars;
